# Generated by Django 5.1 on 2024-11-13 14:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0027_alter_fgsbadpixelstats_source_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystemcharacteristics',
            name='filter_pupil',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='filter and/or pupil name', max_length=7), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='filesystemcharacteristics',
            name='obs_per_filter_pupil',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
